hdfs:
  username: hdfs
  webhdfs:
    host: hadoop-master
    port: 50070

databases:
  default:
    alias: presto

  hive:
    jdbc_driver_class: org.apache.hive.jdbc.HiveDriver
    jdbc_url: jdbc:hive2://hadoop-master:10000
    jdbc_user: hdfs
    jdbc_password: na
    jdbc_pooling: false
    table_manager_type: hive

  presto:
    jdbc_driver_class: com.facebook.presto.jdbc.PrestoDriver
    jdbc_url: jdbc:presto://presto-master:8080/hive/default
    jdbc_user: hdfs
    jdbc_password: na
    jdbc_pooling: false

  psql:
    jdbc_driver_class: org.postgresql.Driver
    jdbc_url: jdbc:postgresql://${DOCKER_MACHINE:-localhost}:15432/postgres
    jdbc_user: blah
    jdbc_password: blah
    jdbc_pooling: true
    table_manager_type: jdbc

  psql2:
    jdbc_driver_class: org.postgresql.Driver
    jdbc_url: jdbc:postgresql://${DOCKER_MACHINE:-localhost}:15433/postgres
    jdbc_user: blah
    jdbc_password: blah
    jdbc_pooling: true
    table_manager_type: jdbc

tests:
  hdfs:
    path: /tempto

ssh:
  identity: ${IDENTITY}
  roles:
    host_by_password:
      host: ${HOST}
      port: 22
      user: ${USER_A}
      password: ${USER_A_PASSWORD}

    host_by_identity:
      host: ${HOST}
      port: 22
      user: ${USER_B}

list:
  string:
    - ala
    - ma
    - kota
